### PR TITLE
Fix location of 2018-12's p2 repository

### PR DESCRIPTION
**Pull request by manandbytes**

### CODE REVIEW

**Comment by martinlippert** [comment]
Thanks for the fix, much appreciated !!!
(please also sign the contributors license agreement, as documented in the contribution guidelines)

**Comment by manandbytes** [comment]
> Thanks for the fix, much appreciated !!!

You're welcome!

> (please also sign the contributors license agreement, as documented in the contribution guidelines)

I think this is a trivial patch that [does not require](https://github.com/spring-projects/eclipse-integration-commons/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement) signing CLA:

> Before we accept a non-trivial patch or pull request we will need you to sign the Contributor License Agreement

**Comment by martinlippert** [comment]
> > (please also sign the contributors license agreement, as documented in the contribution guidelines)
> 
> I think this is a trivial patch that [does not require](https://github.com/spring-projects/eclipse-integration-commons/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement) signing CLA:

Sure, it is a trivial patch, therefore I merged it already a while ago, but signing the contributors license agreement is always a good idea: makes later processing (if necessary) the contributions easier if you just get a green checkmark on all the contributions and you don't need to take a manual look inside to see if this was a trivial patch or not. Again, not required for this one, but would make life easier in case someone would like to double check.

**Comment by manandbytes** [comment]
> but signing the contributors license agreement is always a good idea

Not always but this time it is fine.

**Comment by martinlippert** [comment]
:-)

I know, it might depend on what is written down into the contributors agreement, but generally speaking it is quite important for many open-source projects to keep the project compatible with the license and to allow consumers of the project to use it safely (under the open-source license).

**Pull request merged**
